### ISSUE TITLE
Code Review - Taha

### ISSUE THREAD

**Issue by TahaK** [bounswe/bounswe2015group2#176]
Hi this is my commit to be reviewed https://github.com/silaguler/bounswe2015group2/commit/478966e6613fa36a9418c3eb7d3a19367b76e9b2.

I would greatly appreciate any feedback.

**Comment by CaferTayyar** [comment]
All right, I will review your code and give feedback.

**Comment by CaferTayyar** [comment]
-Code clarity: The code is understandable and there is no unclarity.

-Bugs:
There is no bug in the code. It works excellent.

-Variable names: Variable names are understandable and clear for anybody who looks at the code.

-Indentation: indentation is suitable for conventional coding

-Comments: You should write comments for functions. After you write comments, your code will be more understandable.

**Comment by TahaK** [comment]
I have added documentation as requested https://github.com/bounswe/bounswe2015group2/commit/6a3ed54b149da39ab0fd6736dc1cb311a9fa1419
