### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by onesvat** [bounswe/bounswe2015group2#182]
Could you please review following commits ?

- https://github.com/bounswe/bounswe2015group2/commit/c20a3cf7f9b457fba2d09157dfa536c922f21c6f (List and Add Recipe)

- https://github.com/bounswe/bounswe2015group2/commit/008a85784ce54f0d33bcf83821c027e855c0e1b9 (Search Recipe)

**Comment by mcenkbatman** [comment]
I've already added semantic tagging option to search recipe function so I have already reviewed that commit. I am going to review list and add recipe functions.

**Comment by mcenkbatman** [comment]
-Code clarity: your code is very clear. There is no unnecessary lines.

-Bugs:
in aciktim-web/src/main/java/edu/boun/cmpe451/group2/dao/RecipeDao.java line 39: Map<String, Object> map = this.jdbcTemplate.queryForMap(sql, id);
queryForMap might throw an exception when the id doesn't exist.

-Missing Features: there is no missing feature. the methods all satisfy what is required.

-Coding convention: the response types are changed after that commit. so you were stick to the convention at that time. 

-Variable names: variable names are meaningful and clear.

-Indentation: indentation is perfect.

-Comments: there is no comment but I didn't see any reason to write extra comments.

-Incomplete Code Documentation:your methods need documentation.

-Coverage with unit tests?
There is no test yet. You can create tests for getRecipe methods that takes two valid userIDs one has some number of recipes and one doesn't have any recipe. You can check the post conditions.
