### ISSUE TITLE
General Porject Structure 

### ISSUE THREAD

**Issue by TahaK** [bounswe/bounswe2015group2#64]
I am planning to propose a project structure for Aciktim. All components of the project will be designmed as IntelliJ modules including android application, the backend spring controller and frontend web application.
This will enable us to compile and integrate the project easier and collaborate on various parts of the project more easily. And having the whole project together will give a better idea on where we are on the project
I will create a new branch for this and file a pull request to get feedback from the rest of the team on this issue.

Estimated Time 2 hours

**Comment by onesvat** [comment]
Taha,

It is good idea, I did this but I havent commited yet. There is two main folder in project structure: android and webapp. Both of the folder has individual pom.xml so that they can be builded indepented. Is this the same idea ?

**Comment by TahaK** [comment]
Yes its the same idea but I used gradle in the whole project  so there isn't a pom.xml file they have build.gradle files. I used gradle so that the android application could be build more easily since Android Studio has a better gradle integration

**Comment by TahaK** [comment]
It will be more easy to discuss if I just commit it. I sec

**Comment by onesvat** [comment]
Maybe another solution is using gradle in android folder and maven in webapp folder because I do not know gradle. If it is easy, gradle is okay too. I am waiting

**Comment by TahaK** [comment]
I think it is better if we go with what suits you best . Beacuse you are in the backend team so I don't want to overcomplicate things.

**Comment by TahaK** [comment]
The project strucuture have been finilized
