### ISSUE TITLE
Create Ingredient Table

### ISSUE THREAD

**Issue by TahaK** [bounswe/bounswe2015group2#85]

**Comment by mcenkbatman** [comment]
Started 29.10.2015 23.18
Estimated time to complate: 2 hours

**Comment by mcenkbatman** [comment]
AciktimIngredient table
 id	int(11) unsigned Auto Increment	 
name	varchar(255)	 
protein	float unsigned [0]	 
fat	float unsigned [0]	 
carbohydrate	float unsigned [0]	 
unitID	int(2) unsigned

AciktimIngredientUnit table
id	int(2) unsigned Auto Increment	 
name	varchar(255)

Actual time to complete: 17 hours
